// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// To regenerate this file, run:
/// ```bash
/// flutterfire configure
/// ```
///
/// Make sure to:
/// 1. Create a Firebase project at https://console.firebase.google.com
/// 2. Add your Android app (package: com.savedge.app)
/// 3. Add your iOS app (bundle ID: com.savedge.app)
/// 4. Download google-services.json to android/app/
/// 5. Download GoogleService-Info.plist to ios/Runner/
/// 6. Run `flutterfire configure` to regenerate this file
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJuon9-VIMmVaHgm3xJQzNtJvOd2e0a_Q',
    appId: '1:702662455472:android:f70a119b47fb2e24b14b75',
    messagingSenderId: '702662455472',
    projectId: 'savedge-42c69',
    storageBucket: 'savedge-42c69.firebasestorage.app',
  );

  // Run `flutterfire configure` to generate these values automatically

  // TODO: Replace with your actual Firebase configuration

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrBmeK5X1hIZIuJISWOjAw98jbGOC0IFo',
    appId: '1:702662455472:ios:f5a1d8a61bacc28eb14b75',
    messagingSenderId: '702662455472',
    projectId: 'savedge-42c69',
    storageBucket: 'savedge-42c69.firebasestorage.app',
    iosBundleId: 'com.savedge.savedgeapp',
  );

  // Run `flutterfire configure` to generate these values automatically

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJnjMSzQZ-eN72z4RNVrSHEjBBPHytecY',
    appId: '1:702662455472:web:5a55c9836364ec9eb14b75',
    messagingSenderId: '702662455472',
    projectId: 'savedge-42c69',
    authDomain: 'savedge-42c69.firebaseapp.com',
    storageBucket: 'savedge-42c69.firebasestorage.app',
    measurementId: 'G-MKDPY06SQ0',
  );

}