// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJnjMSzQZ-eN72z4RNVrSHEjBBPHytecY',
    appId: '1:702662455472:web:5a55c9836364ec9eb14b75',
    messagingSenderId: '702662455472',
    projectId: 'savedge-42c69',
    authDomain: 'savedge-42c69.firebaseapp.com',
    storageBucket: 'savedge-42c69.firebasestorage.app',
    measurementId: 'G-MKDPY06SQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJuon9-VIMmVaHgm3xJQzNtJvOd2e0a_Q',
    appId: '1:702662455472:android:f70a119b47fb2e24b14b75',
    messagingSenderId: '702662455472',
    projectId: 'savedge-42c69',
    storageBucket: 'savedge-42c69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrBmeK5X1hIZIuJISWOjAw98jbGOC0IFo',
    appId: '1:702662455472:ios:5c37463674f179c7b14b75',
    messagingSenderId: '702662455472',
    projectId: 'savedge-42c69',
    storageBucket: 'savedge-42c69.firebasestorage.app',
    iosBundleId: 'com.savedge.savedge',
  );
}
